name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Xcode command-line tools
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Build and test
        run: |
          xcodebuild clean test \
          -project TalkALot.xcodeproj \
          -scheme TalkALot \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' \
          -configuration Debug \
          -enableCodeCoverage YES \
          ONLY_ACTIVE_ARCH=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO


